### ISSUE TITLE
Future instance

### ISSUE THREAD

**Issue by mfirry** [typelevel/spotted-leopards#4]
Hi and thanks for this (and everything else you work on).

Coming back from Scala Days, I was experimenting a bit with this sort of things and came out with a silly instance for `Future` along these lines:

```
delegate for Monad[Future] {
  def (fa: Future[A]) map[A, B](f: A => Future[B]): Future[B] =
    fa.map(f)
}
```

My question is how would one go about passing the required `ExecutionContext`.

Thanks!

**Comment by mfirry** [comment]
Hi. I was wondering if anybody had time to help me with this. Otherwise I'll close it, no problem.

**Comment by ChristopherDavenport** [comment]
```
implicit val ec = scala.concurrent.ExecutionContext.global

delegate for Monad[Future] {
  def (fa: Future[A]) map[A, B](f: A => Future[B]): Future[B] =
    fa.map(f)
}
```

Future is a monad, I truly recommend trying to to avoid using at a Monad as how its typically used, side-effecting is not. 

So this is only useful when used in a way future is never actually used as.

Otherwise I think future would need here as well to rely on scala 2 mechanisms at the implicit context is not available.

**Comment by mfirry** [comment]
Thanks so much Christopher!
